[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
solc = "0.8.20"
ffi = true
fs_permissions = [{ access = "read", path = "./img/"}, { access = "read-write", path = "./broadcast" },]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
